<a href="https://colab.research.google.com/github/gayatri-bagusetty/Alogrithm-and-Analysis/blob/main/Strassen_Algorithm_for_matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def split(matrix):
  row, col = matrix.shape
  row2, col2 = row // 2, col // 2
  return matrix[:row2, :col2], matrix[:row2, col2:], matrix[row2:, :col2], matrix[row2:, col2:]

def strassen(A,B):
  if A.shape == (1,1):
    return A * B

  A11, A12, A21, A22 = split(A)
  B11, B12, B21, B22 = split(B)

  M1 = strassen(A11 + A22, B11 + B22)
  M2 = strassen(A21 + A22, B11)
  M3 = strassen(A11, B12 - B22)
  M4 = strassen(A22, B21 - B11)
  M5 = strassen(A11 + A12, B22)
  M6 = strassen(A21 - A11, B11 + B12)
  M7 = strassen(A12 - A22, B21 + B22)

  C11 = M1 + M4 - M5 + M7
  C12 = M3 + M5
  C21 = M2 + M4
  C22 = M1 + M3 - M2 + M6

  top = np.hstack((C11, C12))
  bottom = np.hstack((C21, C22))
  return np.vstack((top, bottom))

def multiply_strassen_4x4(A, B):
  assert A.shape == (4,4) and B.shape == (4,4)
  return strassen(A, B)

A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
B = np.array([[16,15,14,13],[12,11,10,9],[8,7,6,5],[4,3,2,1]])
result = multiply_strassen_4x4(A, B)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nResult of Strassen's Matrix Multiplication:")
print(result)

Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Matrix B:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

Result of Strassen's Matrix Multiplication:
[[ 80  70  60  50]
 [240 214 188 162]
 [400 358 316 274]
 [560 502 444 386]]
